//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medcail_deebo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class APO_TBL
    {
        public decimal APO_ID { get; set; }
        public Nullable<decimal> APO_CODE { get; set; }
        public Nullable<System.DateTime> APO_DATE { get; set; }
        public string APO_TIME { get; set; }
        public string APO_NAME { get; set; }
        public string APO_NOTE { get; set; }
        public Nullable<decimal> CLI_ID { get; set; }
        public Nullable<decimal> CUST_ID { get; set; }
        public Nullable<decimal> DOC_ID { get; set; }
        public Nullable<decimal> VIS_ID { get; set; }
    
        public virtual CLINC_TBL CLINC_TBL { get; set; }
        public virtual CUST_TBL CUST_TBL { get; set; }
        public virtual DOCTORS_TBL DOCTORS_TBL { get; set; }
    }
}
