//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medcail_deebo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARD_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARD_TBL()
        {
            this.CUST_TBL = new HashSet<CUST_TBL>();
        }
    
        public decimal CARD_ID { get; set; }
        public Nullable<decimal> CARD_CODE { get; set; }
        public string CARD_NAME { get; set; }
        public Nullable<System.DateTime> CARD_DATE { get; set; }
        public string CARD_STATE { get; set; }
        public Nullable<int> CARD_PER { get; set; }
        public string CARD_NOTE { get; set; }
        public Nullable<decimal> COM_ID { get; set; }
        public Nullable<decimal> CLI_ID { get; set; }
    
        public virtual CLINC_TBL CLINC_TBL { get; set; }
        public virtual COMPANY_TBL COMPANY_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUST_TBL> CUST_TBL { get; set; }
    }
}
