//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medcail_deebo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLINC_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLINC_TBL()
        {
            this.APO_TBL = new HashSet<APO_TBL>();
            this.CARD_TBL = new HashSet<CARD_TBL>();
            this.COMPANY_TBL = new HashSet<COMPANY_TBL>();
            this.CUST_TBL = new HashSet<CUST_TBL>();
            this.DIAGNOIS_TBL = new HashSet<DIAGNOIS_TBL>();
            this.DIGLIST_TBL = new HashSet<DIGLIST_TBL>();
            this.DOCTORS_TBL = new HashSet<DOCTORS_TBL>();
            this.MEDCHEK_TBL = new HashSet<MEDCHEK_TBL>();
            this.MEDCIN_TBL = new HashSet<MEDCIN_TBL>();
            this.MEDREQ_TBL = new HashSet<MEDREQ_TBL>();
            this.SERLIST_TBL = new HashSet<SERLIST_TBL>();
            this.SERVICE_TBL = new HashSet<SERVICE_TBL>();
            this.USERS_TBL = new HashSet<USERS_TBL>();
            this.VISIT_TBL = new HashSet<VISIT_TBL>();
            this.ORDER_TBL = new HashSet<ORDER_TBL>();
            this.DOS_TBL = new HashSet<DOS_TBL>();
        }
    
        public decimal CLI_ID { get; set; }
        public Nullable<decimal> CLI_CODE { get; set; }
        public string CLI_NAME { get; set; }
        public string CLI_LOC { get; set; }
        public string CLI_NOTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APO_TBL> APO_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARD_TBL> CARD_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPANY_TBL> COMPANY_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUST_TBL> CUST_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIAGNOIS_TBL> DIAGNOIS_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIGLIST_TBL> DIGLIST_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCTORS_TBL> DOCTORS_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDCHEK_TBL> MEDCHEK_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDCIN_TBL> MEDCIN_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDREQ_TBL> MEDREQ_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERLIST_TBL> SERLIST_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICE_TBL> SERVICE_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERS_TBL> USERS_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VISIT_TBL> VISIT_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_TBL> ORDER_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOS_TBL> DOS_TBL { get; set; }
    }
}
