//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medcail_deebo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPANY_TBL()
        {
            this.CARD_TBL = new HashSet<CARD_TBL>();
        }
    
        public decimal COM_ID { get; set; }
        public Nullable<decimal> COM_CODE { get; set; }
        public string COM_NAME { get; set; }
        public string COM_ADDRESS { get; set; }
        public string COM_MOBILE1 { get; set; }
        public string COM_STATE { get; set; }
        public Nullable<decimal> CLI_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARD_TBL> CARD_TBL { get; set; }
        public virtual CLINC_TBL CLINC_TBL { get; set; }
    }
}
