//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medcail_deebo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUST_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUST_TBL()
        {
            this.APO_TBL = new HashSet<APO_TBL>();
            this.MEDLIST_TBL = new HashSet<MEDLIST_TBL>();
            this.VISIT_TBL = new HashSet<VISIT_TBL>();
            this.ORDER_TBL = new HashSet<ORDER_TBL>();
        }
    
        public decimal CUST_ID { get; set; }
        public Nullable<decimal> CUST_CODE { get; set; }
        public string CUST_F_NAME { get; set; }
        public string CUST_S_NAME { get; set; }
        public string CUST_T_NAME { get; set; }
        public string CUST_L_NAME { get; set; }
        public string CUST_AGE { get; set; }
        public Nullable<System.DateTime> CUST_BD { get; set; }
        public string CUST_MOBLIE1 { get; set; }
        public string CUST_MOBILE2 { get; set; }
        public string CUST_ADDRESS { get; set; }
        public string CUST_SAVE_STATE { get; set; }
        public Nullable<decimal> CARD_ID { get; set; }
        public Nullable<decimal> CLI_ID { get; set; }
        public string CUST_NOTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APO_TBL> APO_TBL { get; set; }
        public virtual CARD_TBL CARD_TBL { get; set; }
        public virtual CLINC_TBL CLINC_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDLIST_TBL> MEDLIST_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VISIT_TBL> VISIT_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_TBL> ORDER_TBL { get; set; }
    }
}
