//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medcail_deebo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIGLIST_TBL
    {
        public decimal DIGLIST_ID { get; set; }
        public Nullable<decimal> DIGLIST_CODE { get; set; }
        public string DIGLIST_NAME { get; set; }
        public Nullable<System.DateTime> DIGLIST_DATE { get; set; }
        public string DIGLIST_TIME { get; set; }
        public Nullable<decimal> DIG_ID { get; set; }
        public Nullable<decimal> CUST_ID { get; set; }
        public Nullable<decimal> VIS_ID { get; set; }
        public Nullable<decimal> CLI_ID { get; set; }
    
        public virtual CLINC_TBL CLINC_TBL { get; set; }
        public virtual DIAGNOIS_TBL DIAGNOIS_TBL { get; set; }
        public virtual VISIT_TBL VISIT_TBL { get; set; }
    }
}
