//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medcail_deebo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTORS_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCTORS_TBL()
        {
            this.VISIT_TBL = new HashSet<VISIT_TBL>();
            this.APO_TBL = new HashSet<APO_TBL>();
        }
    
        public decimal DOC_ID { get; set; }
        public Nullable<decimal> DOC_CODE { get; set; }
        public string DOC_NAME { get; set; }
        public string DOC_MAJOR { get; set; }
        public string DOC_EXP { get; set; }
        public Nullable<System.DateTime> DOC_BD { get; set; }
        public string DOC_MOBILE { get; set; }
        public string DOC_ADDRESS { get; set; }
        public Nullable<decimal> CLI_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
    
        public virtual CLINC_TBL CLINC_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VISIT_TBL> VISIT_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APO_TBL> APO_TBL { get; set; }
    }
}
