//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medcail_deebo.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CLINIC_DATABASE_2020Entities : DbContext
    {
        public CLINIC_DATABASE_2020Entities()
            : base("name=CLINIC_DATABASE_2020Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APO_TBL> APO_TBL { get; set; }
        public virtual DbSet<CARD_TBL> CARD_TBL { get; set; }
        public virtual DbSet<CLINC_TBL> CLINC_TBL { get; set; }
        public virtual DbSet<COMPANY_TBL> COMPANY_TBL { get; set; }
        public virtual DbSet<CUST_TBL> CUST_TBL { get; set; }
        public virtual DbSet<DIAGNOIS_TBL> DIAGNOIS_TBL { get; set; }
        public virtual DbSet<DIGLIST_TBL> DIGLIST_TBL { get; set; }
        public virtual DbSet<DOCTORS_TBL> DOCTORS_TBL { get; set; }
        public virtual DbSet<MEDCHEK_TBL> MEDCHEK_TBL { get; set; }
        public virtual DbSet<MEDCIN_TBL> MEDCIN_TBL { get; set; }
        public virtual DbSet<MEDLIST_TBL> MEDLIST_TBL { get; set; }
        public virtual DbSet<MEDREQ_TBL> MEDREQ_TBL { get; set; }
        public virtual DbSet<SERLIST_TBL> SERLIST_TBL { get; set; }
        public virtual DbSet<SERVICE_TBL> SERVICE_TBL { get; set; }
        public virtual DbSet<USERS_TBL> USERS_TBL { get; set; }
        public virtual DbSet<VISIT_TBL> VISIT_TBL { get; set; }
        public virtual DbSet<ORDER_TBL> ORDER_TBL { get; set; }
        public virtual DbSet<DOS_TBL> DOS_TBL { get; set; }
    }
}
