//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medcail_deebo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDCHEK_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDCHEK_TBL()
        {
            this.MEDREQ_TBL = new HashSet<MEDREQ_TBL>();
        }
    
        public decimal MEDCHECK_ID { get; set; }
        public Nullable<decimal> MEDCHEK_CODE { get; set; }
        public string MEDCHEK_NAME { get; set; }
        public string MEDCHEK_TYPE { get; set; }
        public Nullable<decimal> MEDCHEK_PRICE { get; set; }
        public string MEDCHEK_NOTE { get; set; }
        public Nullable<decimal> CLI_ID { get; set; }
    
        public virtual CLINC_TBL CLINC_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDREQ_TBL> MEDREQ_TBL { get; set; }
    }
}
