//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medcail_deebo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDLIST_TBL
    {
        public decimal MEDLIST_ID { get; set; }
        public Nullable<decimal> MEDLIST_CODE { get; set; }
        public string MEDLIST_NAME { get; set; }
        public Nullable<System.DateTime> MEDLIST_DATE { get; set; }
        public Nullable<System.TimeSpan> MEDLIST_TIME { get; set; }
        public Nullable<decimal> MED_ID { get; set; }
        public Nullable<decimal> DOS_ID { get; set; }
        public Nullable<decimal> CUST_ID { get; set; }
        public Nullable<decimal> VIS_ID { get; set; }
    
        public virtual CUST_TBL CUST_TBL { get; set; }
        public virtual MEDCIN_TBL MEDCIN_TBL { get; set; }
        public virtual DOS_TBL DOS_TBL { get; set; }
    }
}
