//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medcail_deebo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_TBL
    {
        public decimal ORDER_ID { get; set; }
        public Nullable<decimal> ORDER_CODE { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public string ORDER_TIME { get; set; }
        public string ORDER_NOTE { get; set; }
        public Nullable<decimal> CUST_ID { get; set; }
        public Nullable<decimal> CLI_ID { get; set; }
    
        public virtual CLINC_TBL CLINC_TBL { get; set; }
        public virtual CUST_TBL CUST_TBL { get; set; }
    }
}
