//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medcail_deebo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERLIST_TBL
    {
        public decimal SERLIST_ID { get; set; }
        public Nullable<decimal> SERLIST_CODE { get; set; }
        public string SERLIST_NAME { get; set; }
        public Nullable<System.DateTime> SERLIST_DATE { get; set; }
        public string SERLIST_TIME { get; set; }
        public Nullable<decimal> SER_PRICE_TOTAL { get; set; }
        public string SERLIST_NOTE { get; set; }
        public Nullable<decimal> SER_ID { get; set; }
        public Nullable<decimal> CLI_ID { get; set; }
        public Nullable<decimal> CUST_ID { get; set; }
        public Nullable<decimal> VIS_ID { get; set; }
    
        public virtual CLINC_TBL CLINC_TBL { get; set; }
        public virtual SERVICE_TBL SERVICE_TBL { get; set; }
    }
}
