//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medcail_deebo.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISIT_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VISIT_TBL()
        {
            this.DIGLIST_TBL = new HashSet<DIGLIST_TBL>();
        }
    
        public decimal VIS_ID { get; set; }
        public Nullable<decimal> VIS_CODE { get; set; }
        public string VIS_NAME { get; set; }
        public Nullable<System.DateTime> VIS_DATE { get; set; }
        public string VIS_TIME { get; set; }
        public string VIS_TYPE { get; set; }
        public Nullable<decimal> CUST_ID { get; set; }
        public Nullable<decimal> CLI_ID { get; set; }
        public Nullable<decimal> DOC_ID { get; set; }
        public Nullable<decimal> VIS_PRICE { get; set; }
        public Nullable<decimal> VIS_DIS_COUNT { get; set; }
        public Nullable<decimal> VIS_TOTAL { get; set; }
        public string VIS_NOTE { get; set; }
        public string VIS_PAY_TYPE { get; set; }
    
        public virtual CLINC_TBL CLINC_TBL { get; set; }
        public virtual CUST_TBL CUST_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIGLIST_TBL> DIGLIST_TBL { get; set; }
        public virtual DOCTORS_TBL DOCTORS_TBL { get; set; }
    }
}
