namespace medcail_deebo.form.form_main
{
    partial class frm_medcin_main
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            DevExpress.XtraEditors.TileItemElement tileItemElement52 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement53 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement54 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame15 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement55 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement56 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement57 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame16 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement58 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement59 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement60 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement61 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement62 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame17 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement63 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement64 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame18 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement65 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement66 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement67 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement68 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement69 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement70 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame19 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement71 = new DevExpress.XtraEditors.TileItemElement();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frm_medcin_main));
            DevExpress.XtraEditors.TileItemFrame tileItemFrame20 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement72 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement73 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement74 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement75 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement76 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement77 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement78 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement79 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame21 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement80 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame22 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement81 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement82 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement83 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement84 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement85 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement86 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame23 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement87 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement88 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame24 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement89 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement90 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement91 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement92 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame25 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement93 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement94 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame26 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement95 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement96 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement97 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement98 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame27 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement99 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement100 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame28 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement101 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement102 = new DevExpress.XtraEditors.TileItemElement();
            this.behaviorManager1 = new DevExpress.Utils.Behaviors.BehaviorManager(this.components);
            this.tileGroup3 = new DevExpress.XtraEditors.TileGroup();
            this.tileControl1 = new DevExpress.XtraEditors.TileControl();
            this.tileGroup2 = new DevExpress.XtraEditors.TileGroup();
            this.tileItem1 = new DevExpress.XtraEditors.TileItem();
            this.tileGroup5 = new DevExpress.XtraEditors.TileGroup();
            this.tileItem4 = new DevExpress.XtraEditors.TileItem();
            this.tileItem2 = new DevExpress.XtraEditors.TileItem();
            this.tileGroup1 = new DevExpress.XtraEditors.TileGroup();
            this.tileItem3 = new DevExpress.XtraEditors.TileItem();
            this.tileItem5 = new DevExpress.XtraEditors.TileItem();
            this.tileItem6 = new DevExpress.XtraEditors.TileItem();
            this.tileItem7 = new DevExpress.XtraEditors.TileItem();
            ((System.ComponentModel.ISupportInitialize)(this.behaviorManager1)).BeginInit();
            this.SuspendLayout();
            // 
            // tileGroup3
            // 
            this.tileGroup3.Name = "tileGroup3";
            // 
            // tileControl1
            // 
            this.tileControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tileControl1.Groups.Add(this.tileGroup2);
            this.tileControl1.Groups.Add(this.tileGroup5);
            this.tileControl1.ItemContentAnimation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            this.tileControl1.Location = new System.Drawing.Point(0, 0);
            this.tileControl1.MaxId = 15;
            this.tileControl1.Name = "tileControl1";
            this.tileControl1.ShowText = true;
            this.tileControl1.Size = new System.Drawing.Size(745, 386);
            this.tileControl1.TabIndex = 1;
            this.tileControl1.Text = "الادوية ";
            this.tileControl1.Click += new System.EventHandler(this.tileControl1_Click);
            // 
            // tileGroup2
            // 
            this.tileGroup2.Items.Add(this.tileItem1);
            this.tileGroup2.Items.Add(this.tileItem7);
            this.tileGroup2.Name = "tileGroup2";
            // 
            // tileItem1
            // 
            this.tileItem1.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.tileItem1.AppearanceItem.Normal.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.tileItem1.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileItem1.CurrentFrameIndex = 1;
            tileItemElement52.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement52.Appearance.Hovered.Options.UseFont = true;
            tileItemElement52.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement52.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement52.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement52.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement52.Appearance.Normal.Options.UseFont = true;
            tileItemElement52.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement52.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement52.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement52.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement52.Appearance.Selected.Options.UseFont = true;
            tileItemElement52.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement52.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement52.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement52.MaxWidth = 160;
            tileItemElement52.Text = "اضافه وتعديل الادويه ";
            tileItemElement52.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement52.TextLocation = new System.Drawing.Point(75, 0);
            tileItemElement53.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement53.Appearance.Hovered.Options.UseFont = true;
            tileItemElement53.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement53.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement53.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement53.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement53.Appearance.Normal.Options.UseFont = true;
            tileItemElement53.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement53.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement53.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement53.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement53.Appearance.Selected.Options.UseFont = true;
            tileItemElement53.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement53.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement53.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement53.MaxWidth = 160;
            tileItemElement53.Text = "التحكم بالادويه ";
            tileItemElement53.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement53.TextLocation = new System.Drawing.Point(75, 27);
            tileItemElement54.ImageOptions.Image = global::medcail_deebo.Properties.Resources.icons8_pill_48px;
            tileItemElement54.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement54.ImageOptions.ImageLocation = new System.Drawing.Point(4, 8);
            tileItemElement54.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement54.ImageOptions.ImageSize = new System.Drawing.Size(64, 64);
            this.tileItem1.Elements.Add(tileItemElement52);
            this.tileItem1.Elements.Add(tileItemElement53);
            this.tileItem1.Elements.Add(tileItemElement54);
            tileItemFrame15.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.SegmentedFade;
            tileItemElement55.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement55.Appearance.Hovered.Options.UseFont = true;
            tileItemElement55.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement55.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement55.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement55.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement55.Appearance.Normal.Options.UseFont = true;
            tileItemElement55.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement55.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement55.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement55.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement55.Appearance.Selected.Options.UseFont = true;
            tileItemElement55.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement55.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement55.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement55.MaxWidth = 160;
            tileItemElement55.Text = "اضافه وتعديل الادويه";
            tileItemElement55.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement55.TextLocation = new System.Drawing.Point(75, 0);
            tileItemElement56.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement56.Appearance.Hovered.Options.UseFont = true;
            tileItemElement56.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement56.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement56.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement56.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement56.Appearance.Normal.Options.UseFont = true;
            tileItemElement56.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement56.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement56.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement56.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement56.Appearance.Selected.Options.UseFont = true;
            tileItemElement56.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement56.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement56.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement56.MaxWidth = 160;
            tileItemElement56.Text = "تسمح لك هذه الواجهه من اضافه وتعديل وحذف الادويه ";
            tileItemElement56.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement56.TextLocation = new System.Drawing.Point(75, 27);
            tileItemElement57.ImageOptions.Image = global::medcail_deebo.Properties.Resources.icons8_pill_48px;
            tileItemElement57.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement57.ImageOptions.ImageLocation = new System.Drawing.Point(4, 8);
            tileItemElement57.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement57.ImageOptions.ImageSize = new System.Drawing.Size(64, 64);
            tileItemFrame15.Elements.Add(tileItemElement55);
            tileItemFrame15.Elements.Add(tileItemElement56);
            tileItemFrame15.Elements.Add(tileItemElement57);
            tileItemFrame16.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement58.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement58.Appearance.Hovered.Options.UseFont = true;
            tileItemElement58.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement58.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement58.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement58.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement58.Appearance.Normal.Options.UseFont = true;
            tileItemElement58.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement58.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement58.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement58.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement58.Appearance.Selected.Options.UseFont = true;
            tileItemElement58.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement58.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement58.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement58.MaxWidth = 160;
            tileItemElement58.Text = "اضافه وتعديل الادويه ";
            tileItemElement58.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement58.TextLocation = new System.Drawing.Point(75, 0);
            tileItemElement59.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement59.Appearance.Hovered.Options.UseFont = true;
            tileItemElement59.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement59.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement59.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement59.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement59.Appearance.Normal.Options.UseFont = true;
            tileItemElement59.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement59.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement59.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement59.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement59.Appearance.Selected.Options.UseFont = true;
            tileItemElement59.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement59.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement59.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement59.MaxWidth = 160;
            tileItemElement59.Text = "التحكم بالادويه ";
            tileItemElement59.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement59.TextLocation = new System.Drawing.Point(75, 27);
            tileItemElement60.ImageOptions.Image = global::medcail_deebo.Properties.Resources.icons8_pill_48px;
            tileItemElement60.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement60.ImageOptions.ImageLocation = new System.Drawing.Point(4, 8);
            tileItemElement60.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement60.ImageOptions.ImageSize = new System.Drawing.Size(64, 64);
            tileItemFrame16.Elements.Add(tileItemElement58);
            tileItemFrame16.Elements.Add(tileItemElement59);
            tileItemFrame16.Elements.Add(tileItemElement60);
            this.tileItem1.Frames.Add(tileItemFrame15);
            this.tileItem1.Frames.Add(tileItemFrame16);
            this.tileItem1.Id = 4;
            this.tileItem1.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem1.Name = "tileItem1";
            this.tileItem1.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileItem1_ItemClick_1);
            // 
            // tileGroup5
            // 
            this.tileGroup5.Items.Add(this.tileItem4);
            this.tileGroup5.Items.Add(this.tileItem6);
            this.tileGroup5.Name = "tileGroup5";
            // 
            // tileItem4
            // 
            this.tileItem4.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.tileItem4.AppearanceItem.Normal.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.tileItem4.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileItem4.Checked = true;
            this.tileItem4.ContentAnimation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            this.tileItem4.CurrentFrameIndex = 1;
            tileItemElement61.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement61.Appearance.Hovered.Options.UseFont = true;
            tileItemElement61.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement61.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement61.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement61.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement61.Appearance.Normal.Options.UseFont = true;
            tileItemElement61.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement61.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement61.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement61.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement61.Appearance.Selected.Options.UseFont = true;
            tileItemElement61.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement61.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement61.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement61.Text = "قائمه الادويه ";
            tileItemElement61.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement61.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement62.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement62.Appearance.Hovered.Options.UseFont = true;
            tileItemElement62.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement62.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement62.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement62.Appearance.Normal.Options.UseFont = true;
            tileItemElement62.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement62.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement62.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement62.Appearance.Selected.Options.UseFont = true;
            tileItemElement62.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement62.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement62.Text = "هذه الواجهه  تقوم بعرض لجميع الادويه  ";
            tileItemElement62.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement62.TextLocation = new System.Drawing.Point(4, 27);
            this.tileItem4.Elements.Add(tileItemElement61);
            this.tileItem4.Elements.Add(tileItemElement62);
            tileItemFrame17.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement63.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement63.Appearance.Hovered.Options.UseFont = true;
            tileItemElement63.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement63.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement63.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement63.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement63.Appearance.Normal.Options.UseFont = true;
            tileItemElement63.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement63.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement63.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement63.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement63.Appearance.Selected.Options.UseFont = true;
            tileItemElement63.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement63.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement63.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement63.Text = "قائمه الادويه ";
            tileItemElement63.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement63.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement64.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement64.Appearance.Hovered.Options.UseFont = true;
            tileItemElement64.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement64.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement64.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement64.Appearance.Normal.Options.UseFont = true;
            tileItemElement64.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement64.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement64.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement64.Appearance.Selected.Options.UseFont = true;
            tileItemElement64.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement64.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement64.Text = "هذه الواجهه الخاصه بعمل عرض لجميع الادويه ";
            tileItemElement64.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement64.TextLocation = new System.Drawing.Point(4, 27);
            tileItemFrame17.Elements.Add(tileItemElement63);
            tileItemFrame17.Elements.Add(tileItemElement64);
            tileItemFrame18.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement65.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement65.Appearance.Hovered.Options.UseFont = true;
            tileItemElement65.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement65.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement65.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement65.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement65.Appearance.Normal.Options.UseFont = true;
            tileItemElement65.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement65.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement65.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement65.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement65.Appearance.Selected.Options.UseFont = true;
            tileItemElement65.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement65.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement65.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement65.Text = "قائمه الادويه ";
            tileItemElement65.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement65.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement66.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement66.Appearance.Hovered.Options.UseFont = true;
            tileItemElement66.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement66.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement66.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement66.Appearance.Normal.Options.UseFont = true;
            tileItemElement66.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement66.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement66.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement66.Appearance.Selected.Options.UseFont = true;
            tileItemElement66.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement66.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement66.Text = "هذه الواجهه  تقوم بعرض لجميع الادويه  ";
            tileItemElement66.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement66.TextLocation = new System.Drawing.Point(4, 27);
            tileItemFrame18.Elements.Add(tileItemElement65);
            tileItemFrame18.Elements.Add(tileItemElement66);
            this.tileItem4.Frames.Add(tileItemFrame17);
            this.tileItem4.Frames.Add(tileItemFrame18);
            this.tileItem4.Id = 10;
            this.tileItem4.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem4.Name = "tileItem4";
            this.tileItem4.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileItem4_ItemClick_1);
            // 
            // tileItem2
            // 
            tileItemElement67.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement67.Appearance.Hovered.Options.UseFont = true;
            tileItemElement67.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement67.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement67.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement67.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement67.Appearance.Normal.Options.UseFont = true;
            tileItemElement67.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement67.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement67.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement67.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement67.Appearance.Selected.Options.UseFont = true;
            tileItemElement67.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement67.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement67.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement67.Text = "Header";
            tileItemElement67.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement67.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement68.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement68.Appearance.Hovered.Options.UseFont = true;
            tileItemElement68.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement68.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement68.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement68.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement68.Appearance.Normal.Options.UseFont = true;
            tileItemElement68.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement68.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement68.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement68.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement68.Appearance.Selected.Options.UseFont = true;
            tileItemElement68.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement68.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement68.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement68.Text = "Text2";
            tileItemElement68.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement68.TextLocation = new System.Drawing.Point(4, 27);
            tileItemElement69.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement69.Appearance.Hovered.Options.UseFont = true;
            tileItemElement69.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement69.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement69.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement69.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement69.Appearance.Normal.Options.UseFont = true;
            tileItemElement69.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement69.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement69.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement69.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement69.Appearance.Selected.Options.UseFont = true;
            tileItemElement69.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement69.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement69.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement69.Text = "Text3";
            tileItemElement69.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement69.TextLocation = new System.Drawing.Point(4, 43);
            tileItemElement70.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement70.Appearance.Hovered.Options.UseFont = true;
            tileItemElement70.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement70.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement70.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement70.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement70.Appearance.Normal.Options.UseFont = true;
            tileItemElement70.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement70.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement70.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement70.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement70.Appearance.Selected.Options.UseFont = true;
            tileItemElement70.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement70.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement70.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement70.Text = "Text4";
            tileItemElement70.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement70.TextLocation = new System.Drawing.Point(4, 59);
            this.tileItem2.Elements.Add(tileItemElement67);
            this.tileItem2.Elements.Add(tileItemElement68);
            this.tileItem2.Elements.Add(tileItemElement69);
            this.tileItem2.Elements.Add(tileItemElement70);
            tileItemFrame19.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement71.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image")));
            tileItemElement71.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement71.ImageOptions.ImageLocation = new System.Drawing.Point(-12, -8);
            tileItemElement71.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement71.ImageOptions.ImageSize = new System.Drawing.Size(120, 120);
            tileItemFrame19.Elements.Add(tileItemElement71);
            tileItemFrame19.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame19.Image")));
            tileItemFrame20.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement72.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement72.Appearance.Hovered.Options.UseFont = true;
            tileItemElement72.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement72.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement72.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement72.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement72.Appearance.Normal.Options.UseFont = true;
            tileItemElement72.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement72.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement72.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement72.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement72.Appearance.Selected.Options.UseFont = true;
            tileItemElement72.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement72.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement72.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement72.Text = "Header";
            tileItemElement72.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement72.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement73.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement73.Appearance.Hovered.Options.UseFont = true;
            tileItemElement73.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement73.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement73.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement73.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement73.Appearance.Normal.Options.UseFont = true;
            tileItemElement73.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement73.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement73.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement73.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement73.Appearance.Selected.Options.UseFont = true;
            tileItemElement73.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement73.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement73.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement73.Text = "Text2";
            tileItemElement73.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement73.TextLocation = new System.Drawing.Point(4, 27);
            tileItemElement74.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement74.Appearance.Hovered.Options.UseFont = true;
            tileItemElement74.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement74.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement74.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement74.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement74.Appearance.Normal.Options.UseFont = true;
            tileItemElement74.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement74.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement74.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement74.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement74.Appearance.Selected.Options.UseFont = true;
            tileItemElement74.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement74.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement74.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement74.Text = "Text3";
            tileItemElement74.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement74.TextLocation = new System.Drawing.Point(4, 43);
            tileItemElement75.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement75.Appearance.Hovered.Options.UseFont = true;
            tileItemElement75.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement75.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement75.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement75.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement75.Appearance.Normal.Options.UseFont = true;
            tileItemElement75.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement75.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement75.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement75.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement75.Appearance.Selected.Options.UseFont = true;
            tileItemElement75.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement75.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement75.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement75.Text = "Text4";
            tileItemElement75.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement75.TextLocation = new System.Drawing.Point(4, 59);
            tileItemFrame20.Elements.Add(tileItemElement72);
            tileItemFrame20.Elements.Add(tileItemElement73);
            tileItemFrame20.Elements.Add(tileItemElement74);
            tileItemFrame20.Elements.Add(tileItemElement75);
            this.tileItem2.Frames.Add(tileItemFrame19);
            this.tileItem2.Frames.Add(tileItemFrame20);
            this.tileItem2.Id = 1;
            this.tileItem2.ItemSize = DevExpress.XtraEditors.TileItemSize.Medium;
            this.tileItem2.Name = "tileItem2";
            // 
            // tileGroup1
            // 
            this.tileGroup1.Name = "tileGroup1";
            // 
            // tileItem3
            // 
            tileItemElement76.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement76.Appearance.Hovered.Options.UseFont = true;
            tileItemElement76.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement76.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement76.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement76.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement76.Appearance.Normal.Options.UseFont = true;
            tileItemElement76.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement76.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement76.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement76.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement76.Appearance.Selected.Options.UseFont = true;
            tileItemElement76.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement76.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement76.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement76.Text = "Header";
            tileItemElement76.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement76.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement77.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement77.Appearance.Hovered.Options.UseFont = true;
            tileItemElement77.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement77.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement77.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement77.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement77.Appearance.Normal.Options.UseFont = true;
            tileItemElement77.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement77.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement77.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement77.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement77.Appearance.Selected.Options.UseFont = true;
            tileItemElement77.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement77.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement77.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement77.Text = "Text2";
            tileItemElement77.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement77.TextLocation = new System.Drawing.Point(4, 27);
            tileItemElement78.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement78.Appearance.Hovered.Options.UseFont = true;
            tileItemElement78.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement78.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement78.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement78.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement78.Appearance.Normal.Options.UseFont = true;
            tileItemElement78.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement78.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement78.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement78.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement78.Appearance.Selected.Options.UseFont = true;
            tileItemElement78.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement78.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement78.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement78.Text = "Text3";
            tileItemElement78.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement78.TextLocation = new System.Drawing.Point(4, 43);
            tileItemElement79.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement79.Appearance.Hovered.Options.UseFont = true;
            tileItemElement79.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement79.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement79.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement79.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement79.Appearance.Normal.Options.UseFont = true;
            tileItemElement79.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement79.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement79.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement79.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement79.Appearance.Selected.Options.UseFont = true;
            tileItemElement79.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement79.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement79.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement79.Text = "Text4";
            tileItemElement79.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement79.TextLocation = new System.Drawing.Point(4, 59);
            this.tileItem3.Elements.Add(tileItemElement76);
            this.tileItem3.Elements.Add(tileItemElement77);
            this.tileItem3.Elements.Add(tileItemElement78);
            this.tileItem3.Elements.Add(tileItemElement79);
            tileItemFrame21.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement80.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image1")));
            tileItemElement80.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement80.ImageOptions.ImageLocation = new System.Drawing.Point(-12, -8);
            tileItemElement80.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement80.ImageOptions.ImageSize = new System.Drawing.Size(120, 120);
            tileItemFrame21.Elements.Add(tileItemElement80);
            tileItemFrame21.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame21.Image")));
            tileItemFrame22.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement81.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement81.Appearance.Hovered.Options.UseFont = true;
            tileItemElement81.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement81.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement81.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement81.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement81.Appearance.Normal.Options.UseFont = true;
            tileItemElement81.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement81.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement81.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement81.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement81.Appearance.Selected.Options.UseFont = true;
            tileItemElement81.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement81.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement81.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement81.Text = "Header";
            tileItemElement81.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement81.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement82.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement82.Appearance.Hovered.Options.UseFont = true;
            tileItemElement82.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement82.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement82.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement82.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement82.Appearance.Normal.Options.UseFont = true;
            tileItemElement82.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement82.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement82.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement82.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement82.Appearance.Selected.Options.UseFont = true;
            tileItemElement82.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement82.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement82.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement82.Text = "Text2";
            tileItemElement82.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement82.TextLocation = new System.Drawing.Point(4, 27);
            tileItemElement83.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement83.Appearance.Hovered.Options.UseFont = true;
            tileItemElement83.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement83.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement83.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement83.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement83.Appearance.Normal.Options.UseFont = true;
            tileItemElement83.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement83.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement83.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement83.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement83.Appearance.Selected.Options.UseFont = true;
            tileItemElement83.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement83.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement83.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement83.Text = "Text3";
            tileItemElement83.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement83.TextLocation = new System.Drawing.Point(4, 43);
            tileItemElement84.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement84.Appearance.Hovered.Options.UseFont = true;
            tileItemElement84.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement84.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement84.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement84.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement84.Appearance.Normal.Options.UseFont = true;
            tileItemElement84.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement84.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement84.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement84.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement84.Appearance.Selected.Options.UseFont = true;
            tileItemElement84.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement84.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement84.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement84.Text = "Text4";
            tileItemElement84.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement84.TextLocation = new System.Drawing.Point(4, 59);
            tileItemFrame22.Elements.Add(tileItemElement81);
            tileItemFrame22.Elements.Add(tileItemElement82);
            tileItemFrame22.Elements.Add(tileItemElement83);
            tileItemFrame22.Elements.Add(tileItemElement84);
            this.tileItem3.Frames.Add(tileItemFrame21);
            this.tileItem3.Frames.Add(tileItemFrame22);
            this.tileItem3.Id = 1;
            this.tileItem3.ItemSize = DevExpress.XtraEditors.TileItemSize.Medium;
            this.tileItem3.Name = "tileItem3";
            // 
            // tileItem5
            // 
            this.tileItem5.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.tileItem5.AppearanceItem.Normal.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.tileItem5.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileItem5.Checked = true;
            this.tileItem5.ContentAnimation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement85.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement85.Appearance.Hovered.Options.UseFont = true;
            tileItemElement85.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement85.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement85.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement85.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement85.Appearance.Normal.Options.UseFont = true;
            tileItemElement85.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement85.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement85.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement85.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement85.Appearance.Selected.Options.UseFont = true;
            tileItemElement85.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement85.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement85.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement85.Text = "قائمه الادويه ";
            tileItemElement85.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement85.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement86.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement86.Appearance.Hovered.Options.UseFont = true;
            tileItemElement86.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement86.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement86.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement86.Appearance.Normal.Options.UseFont = true;
            tileItemElement86.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement86.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement86.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement86.Appearance.Selected.Options.UseFont = true;
            tileItemElement86.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement86.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement86.Text = "هذه الواجهه الخاصه بعمل عرض لجميع الادويه ";
            tileItemElement86.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement86.TextLocation = new System.Drawing.Point(4, 27);
            this.tileItem5.Elements.Add(tileItemElement85);
            this.tileItem5.Elements.Add(tileItemElement86);
            tileItemFrame23.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement87.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement87.Appearance.Hovered.Options.UseFont = true;
            tileItemElement87.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement87.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement87.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement87.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement87.Appearance.Normal.Options.UseFont = true;
            tileItemElement87.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement87.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement87.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement87.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement87.Appearance.Selected.Options.UseFont = true;
            tileItemElement87.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement87.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement87.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement87.Text = "قائمه الادويه ";
            tileItemElement87.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement87.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement88.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement88.Appearance.Hovered.Options.UseFont = true;
            tileItemElement88.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement88.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement88.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement88.Appearance.Normal.Options.UseFont = true;
            tileItemElement88.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement88.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement88.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement88.Appearance.Selected.Options.UseFont = true;
            tileItemElement88.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement88.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement88.Text = "هذه الواجهه الخاصه بعمل عرض لجميع الادويه ";
            tileItemElement88.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement88.TextLocation = new System.Drawing.Point(4, 27);
            tileItemFrame23.Elements.Add(tileItemElement87);
            tileItemFrame23.Elements.Add(tileItemElement88);
            tileItemFrame24.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement89.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement89.Appearance.Hovered.Options.UseFont = true;
            tileItemElement89.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement89.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement89.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement89.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement89.Appearance.Normal.Options.UseFont = true;
            tileItemElement89.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement89.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement89.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement89.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement89.Appearance.Selected.Options.UseFont = true;
            tileItemElement89.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement89.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement89.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement89.Text = "قائمه الادويه ";
            tileItemElement89.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement89.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement90.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement90.Appearance.Hovered.Options.UseFont = true;
            tileItemElement90.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement90.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement90.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement90.Appearance.Normal.Options.UseFont = true;
            tileItemElement90.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement90.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement90.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement90.Appearance.Selected.Options.UseFont = true;
            tileItemElement90.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement90.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement90.Text = "هذه الواجهه  تقوم بعرض لجميع الادويه  ";
            tileItemElement90.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement90.TextLocation = new System.Drawing.Point(4, 27);
            tileItemFrame24.Elements.Add(tileItemElement89);
            tileItemFrame24.Elements.Add(tileItemElement90);
            this.tileItem5.Frames.Add(tileItemFrame23);
            this.tileItem5.Frames.Add(tileItemFrame24);
            this.tileItem5.Id = 10;
            this.tileItem5.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem5.Name = "tileItem5";
            // 
            // tileItem6
            // 
            this.tileItem6.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.tileItem6.AppearanceItem.Normal.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.tileItem6.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileItem6.CurrentFrameIndex = 1;
            tileItemElement91.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement91.Appearance.Hovered.Options.UseFont = true;
            tileItemElement91.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement91.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement91.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement91.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement91.Appearance.Normal.Options.UseFont = true;
            tileItemElement91.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement91.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement91.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement91.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement91.Appearance.Selected.Options.UseFont = true;
            tileItemElement91.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement91.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement91.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement91.MaxWidth = 160;
            tileItemElement91.Text = "الوصفات الطبيه ";
            tileItemElement91.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement91.TextLocation = new System.Drawing.Point(75, 0);
            tileItemElement92.ImageOptions.Image = global::medcail_deebo.Properties.Resources.icons8_medical_history_96px;
            tileItemElement92.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement92.ImageOptions.ImageLocation = new System.Drawing.Point(4, 8);
            tileItemElement92.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement92.ImageOptions.ImageSize = new System.Drawing.Size(64, 64);
            this.tileItem6.Elements.Add(tileItemElement91);
            this.tileItem6.Elements.Add(tileItemElement92);
            tileItemFrame25.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement93.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement93.Appearance.Hovered.Options.UseFont = true;
            tileItemElement93.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement93.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement93.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement93.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement93.Appearance.Normal.Options.UseFont = true;
            tileItemElement93.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement93.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement93.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement93.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement93.Appearance.Selected.Options.UseFont = true;
            tileItemElement93.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement93.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement93.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement93.MaxWidth = 160;
            tileItemElement93.Text = "الوصفات الطبيه ";
            tileItemElement93.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement93.TextLocation = new System.Drawing.Point(75, 0);
            tileItemElement94.ImageOptions.Image = global::medcail_deebo.Properties.Resources.icons8_medical_history_96px;
            tileItemElement94.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement94.ImageOptions.ImageLocation = new System.Drawing.Point(4, 8);
            tileItemElement94.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement94.ImageOptions.ImageSize = new System.Drawing.Size(64, 64);
            tileItemFrame25.Elements.Add(tileItemElement93);
            tileItemFrame25.Elements.Add(tileItemElement94);
            tileItemFrame26.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement95.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement95.Appearance.Hovered.Options.UseFont = true;
            tileItemElement95.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement95.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement95.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement95.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement95.Appearance.Normal.Options.UseFont = true;
            tileItemElement95.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement95.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement95.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement95.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement95.Appearance.Selected.Options.UseFont = true;
            tileItemElement95.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement95.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement95.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement95.MaxWidth = 160;
            tileItemElement95.Text = "الوصفات الطبيه ";
            tileItemElement95.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement95.TextLocation = new System.Drawing.Point(75, 0);
            tileItemElement96.ImageOptions.Image = global::medcail_deebo.Properties.Resources.icons8_medical_history_96px;
            tileItemElement96.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement96.ImageOptions.ImageLocation = new System.Drawing.Point(4, 8);
            tileItemElement96.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement96.ImageOptions.ImageSize = new System.Drawing.Size(64, 64);
            tileItemFrame26.Elements.Add(tileItemElement95);
            tileItemFrame26.Elements.Add(tileItemElement96);
            this.tileItem6.Frames.Add(tileItemFrame25);
            this.tileItem6.Frames.Add(tileItemFrame26);
            this.tileItem6.Id = 13;
            this.tileItem6.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem6.Name = "tileItem6";
            this.tileItem6.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileItem6_ItemClick);
            // 
            // tileItem7
            // 
            this.tileItem7.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.tileItem7.AppearanceItem.Normal.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.tileItem7.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement97.ImageOptions.Image = global::medcail_deebo.Properties.Resources.icons8_hospital_room_100px;
            tileItemElement97.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement97.ImageOptions.ImageLocation = new System.Drawing.Point(-12, -8);
            tileItemElement97.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement97.ImageOptions.ImageSize = new System.Drawing.Size(248, 120);
            tileItemElement98.Text = "";
            this.tileItem7.Elements.Add(tileItemElement97);
            this.tileItem7.Elements.Add(tileItemElement98);
            tileItemFrame27.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemElement99.ImageOptions.Image = global::medcail_deebo.Properties.Resources.icons8_hospital_room_100px;
            tileItemElement99.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement99.ImageOptions.ImageLocation = new System.Drawing.Point(-12, -8);
            tileItemElement99.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement99.ImageOptions.ImageSize = new System.Drawing.Size(248, 120);
            tileItemElement100.Text = "";
            tileItemFrame27.Elements.Add(tileItemElement99);
            tileItemFrame27.Elements.Add(tileItemElement100);
            tileItemFrame27.Image = global::medcail_deebo.Properties.Resources.icons8_hospital_room_100px;
            tileItemFrame28.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement101.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement101.Appearance.Hovered.Options.UseFont = true;
            tileItemElement101.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement101.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement101.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement101.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement101.Appearance.Normal.Options.UseFont = true;
            tileItemElement101.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement101.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement101.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement101.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement101.Appearance.Selected.Options.UseFont = true;
            tileItemElement101.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement101.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement101.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement101.MaxWidth = 160;
            tileItemElement101.Text = "صرف الادوية ";
            tileItemElement101.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement101.TextLocation = new System.Drawing.Point(75, 0);
            tileItemElement102.ImageOptions.Image = global::medcail_deebo.Properties.Resources.icons8_pharmacist_96px;
            tileItemElement102.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement102.ImageOptions.ImageLocation = new System.Drawing.Point(4, 8);
            tileItemElement102.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomOutside;
            tileItemElement102.ImageOptions.ImageSize = new System.Drawing.Size(64, 64);
            tileItemFrame28.Elements.Add(tileItemElement101);
            tileItemFrame28.Elements.Add(tileItemElement102);
            this.tileItem7.Frames.Add(tileItemFrame27);
            this.tileItem7.Frames.Add(tileItemFrame28);
            this.tileItem7.Id = 14;
            this.tileItem7.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem7.Name = "tileItem7";
            this.tileItem7.ItemClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileItem7_ItemClick);
            // 
            // frm_medcin_main
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(745, 386);
            this.Controls.Add(this.tileControl1);
            this.Name = "frm_medcin_main";
            this.Text = "frm_medcin_main";
            ((System.ComponentModel.ISupportInitialize)(this.behaviorManager1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private DevExpress.Utils.Behaviors.BehaviorManager behaviorManager1;
        private DevExpress.XtraEditors.TileGroup tileGroup3;
        private DevExpress.XtraEditors.TileControl tileControl1;
        private DevExpress.XtraEditors.TileGroup tileGroup2;
        private DevExpress.XtraEditors.TileItem tileItem1;
        private DevExpress.XtraEditors.TileGroup tileGroup5;
        private DevExpress.XtraEditors.TileItem tileItem4;
        private DevExpress.XtraEditors.TileItem tileItem2;
        private DevExpress.XtraEditors.TileGroup tileGroup1;
        private DevExpress.XtraEditors.TileItem tileItem3;
        private DevExpress.XtraEditors.TileItem tileItem7;
        private DevExpress.XtraEditors.TileItem tileItem6;
        private DevExpress.XtraEditors.TileItem tileItem5;
    }
}